#!/bin/bash -e

SELFDIR=$(dirname $(readlink -f $0))
SCRIPT=${SCRIPT:=./run}

SERVICES="\
  mender-inventory \
  mender-useradm \
  mender-device-auth \
  mender-device-adm \
  mender-deployments \
"
DB_SERVICES="\
  mender-mongo-useradm \
  mender-mongo-inventory \
  mender-mongo-device-adm \
  mender-mongo-device-auth \
  mender-mongo-deployments \
"

# stop service that are using DBs
${SCRIPT} stop ${SERVICES}

DATEFMT="+%Y-%m-%d-%H:%M:%S"
BACKUP_DIR="db-backup-$(date ${DATEFMT})"
REAL_BACKUP_DIR="$(readlink -f ${SELFDIR}/../${BACKUP_DIR})"

# dump DB, volume is mounted wrt. the main compose file which is at ..
${SCRIPT} -f ${SELFDIR}/migration-helper.yml \
          run \
          --rm \
          -e DB_SERVICES="${DB_SERVICES}" \
          -e BACKUP_DIR="${BACKUP_DIR}" \
          mongo-helper \
          sh -c 'for s in ${DB_SERVICES}; do mongodump -h "$s" --out /srv/${BACKUP_DIR}/${s}; done'

echo "-- DB dump saved to ${REAL_BACKUP_DIR}"
